### PR TITLE
pkp/pkp-lib#5610 Change publish and publication related translations …

### PR DESCRIPTION
**Pull request by ajnyga**
…to post and preprint

ping @NateWr @asmecher

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher wonder if this breaks the tests because some of the labels change?

**Comment by asmecher** [comment]
> wonder if this breaks the tests because some of the labels change?

Yes, definitely:
```
$ find cypress -type f -exec fgrep -l -i publish "{}" ";"
cypress/tests/data/60-content/ZwoodsSubmission.spec.js
cypress/tests/data/60-content/JmwandengaSubmission.spec.js
cypress/tests/data/60-content/DsokoloffSubmission.spec.js
cypress/tests/data/60-content/JnovakSubmission.spec.js
cypress/tests/data/60-content/LchristopherSubmission.spec.js
cypress/tests/data/60-content/RrossiSubmission.spec.js
cypress/tests/data/60-content/VwilliamsonSubmission.spec.js
cypress/tests/data/60-content/EostromSubmission.spec.js
cypress/tests/data/60-content/KalkhafajiSubmission.spec.js
cypress/tests/data/60-content/PdanielSubmission.spec.js
cypress/tests/data/60-content/FpaglieriSubmission.spec.js
cypress/tests/data/60-content/RbaiyewuSubmission.spec.js
cypress/tests/data/60-content/DdioufSubmission.spec.js
cypress/tests/data/60-content/DphillipsSubmission.spec.js
cypress/tests/data/60-content/CkwantesSubmission.spec.js
cypress/tests/data/60-content/LkumiegaSubmission.spec.js
cypress/tests/data/60-content/VkarbasizaedSubmission.spec.js
cypress/tests/data/60-content/CmontgomerieSubmission.spec.js
```
Looking at one example:
```
cy.get('ul.pkp_workflow_decisions button:contains("Schedule For Publication")').click();
cy.get('div.pkpPublication button:contains("Publish"):visible').click();
cy.get('div:contains("All requirements have been met. Are you sure you want to publish this?")');
cy.get('[id^="publish"] button:contains("Publish")').click();
```
Luckily these are app-specific and can be easily adjusted in the same repo. There may be more, but this is a good place to start.

**Comment by ajnyga** [comment]
Ok, so I will couple this pr with a change to those references.

**Comment by ajnyga** [comment]
Restarted tests

**Comment by asmecher** [comment]
Manually merged/cherry-picked!

**Pull request closed without merging**
