### PR TITLE
pkp/pkp-lib#6759 Rename OJS related variables in the code

### PR DESCRIPTION
**Pull request by ajnyga**
@asmecher first try with this, I will buy the whole dev team a beer in the next Sprint if the tests will not fail.

### CODE REVIEW

**Comment by ajnyga** [comment]
These need to be changed during an upgrade:

`filters` table
Replace `plugins.metadata.dc11.filter.Dc11SchemaArticleAdapter`
Replace `plugins.importexport.crossref.filter.ArticleCrossrefXmlFilter`

`files` table
Replace values like `/article/` in `path` field

`filter_groups` table
Replace `article=>dc11	plugins.metadata.dc11.articleAdapter.displayName	plugins.metadata.dc11.articleAdapter.description	class::classes.submission.Submission	metadata::plugins.metadata.dc11.schema.Dc11Schema(ARTICLE)`
Replace `article=>crossref-xml	plugins.importexport.crossref.displayName	plugins.importexport.crossref.description	class::classes.submission.Submission[]	xml::schema(https://www.crossref.org/schemas/crossref4.3.6.xsd)`

`public` folder
Rename `journals` folder (I would suggest renaming this to `contexts` in OPS and we can follow the same logic later in OJS and OMP)

`files` folder
Rename `journals` folder (I would suggest renaming this to `contexts` in OPS and we can follow the same logic later in OJS and OMP) 
Rename `articles` folder (I would suggest renaming this to `submissions` in OPS and we can follow the same logic later in OJS and OMP) 

(Renaming to contex/submission of course requires us to do some additional changes to the pull request)

Can you think of anything else that needs to be changed during an upgrade @asmecher ?

**Comment by asmecher** [comment]
@ajnyga, does https://github.com/pkp/ops/pull/122/checks?check_run_id=1901547212 mean what I think it does? :beers:

I think the tables you've identified plus the couple of directories are the only obscure parts needing fixing.
As for table renames, I think the really tough ones (`versions`, `plugin_settings`, etc) are fine -- a migration should be able to take care of it: https://laravel.com/docs/7.x/migrations#renaming-and-dropping-tables

There may be some challenges with index and sequence names being updated with a table rename; it might be worth comparing an upgraded database against a fresh install once you've got the migration in place to rename tables.

**Comment by ajnyga** [comment]
Ok, I will prepare an upgrade script for those.

I realized that there might already be a contexts folder present in an installation. I think the code for library files uses that? So I would first have to rename that folder to something else, then rename journals to contexts and the move the contents of the old contexts folder to the new one?

> @ajnyga, does https://github.com/pkp/ops/pull/122/checks?check_run_id=1901547212 mean what I think it does? 🍻
I do not know what you mean? By the way, how many members does the dev team have?

**Comment by ajnyga** [comment]
@asmecher can you check the migration stuff, it is in the last commit. Not sure how you want it done.

**Comment by asmecher** [comment]
Thanks, @ajnyga, the migration looks good. There's a note here about restructuring these for the future: https://github.com/pkp/pkp-lib/pull/6787#discussion_r585709826
This will help people recover from a broken upgrade, and bring us in line with migrations best practices, which seem to be to include fine-grained migrations in separate files.

**Comment by ajnyga** [comment]
Do you want me to move the migration to a separate issue specific file?

**Comment by asmecher** [comment]
> Do you want me to move the migration to a separate issue specific file?

Yes, please do!

**Comment by asmecher** [comment]
@ajnyga, this looks good -- the test failures are upstream of your work, I think. I took the liberty of rebasing your work to fix these and we'll see if it gets further: https://github.com/pkp/ops/pull/132

**Comment by asmecher** [comment]
aaaaand https://github.com/pkp/ops/pull/132 passed so I merged it! Closing this one...

**Pull request closed without merging**
