### PR TITLE
pkp/pkp-lib#7176 Fix POSTED_ACK recipient

### PR DESCRIPTION
**Pull request by ajnyga**
https://github.com/pkp/pkp-lib/issues/7176

ping @asmecher

### CODE REVIEW

**Comment by ajnyga** [comment]
ping @asmecher just one test failed if you can restart that

**Comment by asmecher** [comment]
Looks like someone else already restarted it? In any case, let me know if this is ready for review/merge.

**Comment by asmecher** [comment]
Thanks, @ajnyga! I presume you're testing against `main` when commits are to be merged there?

**Comment by ajnyga** [comment]
Yes I did, do you want me to do a pr for 3.3 stable? I think the code is in a different file in that version.

**Comment by asmecher** [comment]
No, I'm happy with a merge to `main` for this one, thanks!

**Pull request merged**
