### PR TITLE
Add decline action for moderators pkp/pkp-lib#5715 

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by ajnyga** [comment]
ping @asmecher seems that tests are stuck?

**Comment by asmecher** [comment]
@ajnyga, the tests appear to be queued -- they'll run in a bit, unless Travis is having queuing/VM problems.

**Comment by ajnyga** [comment]
i think your submodule update from yesterday had been in queu for 10 hours when I started working today. Could be I am mistaken

**Comment by asmecher** [comment]
Hmm, I don't see any backlog now (everything is tested) but I still can't get those tests to start. Is there anything still running on your Travis panel?

**Pull request merged**
