### PR TITLE
pkp/pkp-lib#5819 Add Revert Decline form 

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by ajnyga** [comment]
ping @NateWr @asmecher 

This is the Revert Decision form for all three apps. The initial pr is just for OPS. Can you check that the concept is ok and I will add a pr for OJS and OMP as well. It does not require much work.

I am now passing `$submission` to `getStageDecisions` which allows me to control whether I should show the Decline or the Revert Decline button. Also you can not Decline a published or scheduled submission now.

**Comment by NateWr** [comment]
Just real quick I notice that you're missing the `#` in your commit messages. It should be `pkp/pkp-lib#5819` so that it shows up in the issue history.

**Comment by NateWr** [comment]
@asmecher I'll take this one as you've got enough on your plate.

**Comment by ajnyga** [comment]
Oh, yeah I have a problem with my keyboard, with key 3... Sometimes works, sometimes not...

**Comment by NateWr** [comment]
I'm getting the following error when running this branch:

```
[24-Nov-2020 17:01:54 Europe/London] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Connection::prepareBindings() must be of the type array, int given, called in /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php on line 364 and defined in /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php:593
Stack trace:
#0 /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php(364): Illuminate\Database\Connection->prepareBindings(1)
#1 /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\Query\Expression), 1)
#2 /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback(Object(Illuminate\Database\Query\Expression), 1, Object(Closure))
#3 /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php(373): Illuminate\Database\Connection->run( in /home/nate/Projects/pkp/ops/lib/pkp/lib/vendor/illuminate/database/Connection.php on line 593
```

Is there no `lib/pkp` PR that I should be using?

**Comment by ajnyga** [comment]
Yes, this one: https://github.com/pkp/pkp-lib/pull/6354
I guess a change in master has created a conflict. I will rebase tomorrow.

**Comment by asmecher** [comment]
If it helps you track this down, the error:
> Uncaught TypeError: Argument 1 passed to Illuminate\Database\Connection::prepareBindings() must be of the type array

...comes from the ADODB removal (https://github.com/pkp/pkp-lib/issues/6264), and the following advice is noted there:
> If you are only binding a single parameter to a query, you now need to put it in an array, where ADODB would accept either a literal or an array. (See e.g. [`ContextDAO::getByPath`](https://github.com/pkp/pkp-lib/pull/6318/files#diff-68705a011bd376cb3d885f8f2568cbe7dc4b4fcc624a8423fd6286829e483e08R63).) You will see `Argument 1 passed to Illuminate\Database\Connection::prepareBindings() must be of the type array` if you need to adjust this.

**Pull request merged**
