### PR TITLE
pkp/pkp-lib#6915 Use Facade instead of Database Capsule

### PR DESCRIPTION
**Pull request by Vitaliy-1**

### CODE REVIEW

**Comment by asmecher** [comment]
@Vitaliy-1, I think you missed a case in `classes/services/queryBuilders/GalleyQueryBuilder.inc.php` where `Capsule::table` is still called.

**Comment by asmecher** [comment]
Actually, there are two leftover cases. If you add https://github.com/asmecher/ops/commit/a09e1c435b634108bddc0246e0cc502a47bd0d8b to your PR, it should fix the tests.

**Comment by Vitaliy-1** [comment]
Thanks, Alec. Missed that.

**Comment by Vitaliy-1** [comment]
Looks like the test script tries to find an element that doesn't exist in OPS. According to the local check, all other tests are successful.

**Pull request merged**
