### PR TITLE
Initial OPS Modifications for Inclusion of Moderator Role

### PR DESCRIPTION
**Pull request by ajnyga**
https://github.com/pkp/pkp-lib/issues/5622

### CODE REVIEW

**Comment by asmecher** [comment]
Looks good, thanks, @ajnyga (and I'm happy that this can be done just in the application repo). Can you mark the translations in other languages "fuzzy" in the `.po` files? Then it's ready for merging (and cherry-picking to `stable-3_2_0` if you like).

**Comment by ajnyga** [comment]
Sure I will mark the changed keys fuzzy.

I will also do a small adjustements so that only the frontend will be talking about "Posting" and the backend will stay as it is, with "Publish".

**Comment by ajnyga** [comment]
@asmecher tests are not starting for some reason. Local test were ok, so I will merge this anyway and cherry-pick to stable.

**Comment by ajnyga** [comment]
Merged and cherry-picked to 3_2_0

**Pull request merged**
